//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotVisio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotVisio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ActionsGroup {
            get {
                return ResourceManager.GetString("ActionsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string AdvancedGroup {
            get {
                return ResourceManager.GetString("AdvancedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        internal static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        internal static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect Ratio.
        /// </summary>
        internal static string AspectRatio {
            get {
                return ResourceManager.GetString("AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export DOT.
        /// </summary>
        internal static string BtnExportDot {
            get {
                return ResourceManager.GetString("BtnExportDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import DOT.
        /// </summary>
        internal static string BtnImportDot {
            get {
                return ResourceManager.GetString("BtnImportDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import DOT using GraphViz.
        /// </summary>
        internal static string BtnImportDotGraphViz {
            get {
                return ResourceManager.GetString("BtnImportDotGraphViz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout using GraphViz.
        /// </summary>
        internal static string BtnLayoutWithGraphViz {
            get {
                return ResourceManager.GetString("BtnLayoutWithGraphViz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate Bounding Boxes.
        /// </summary>
        internal static string BtnRedrawBoundingBoxes {
            get {
                return ResourceManager.GetString("BtnRedrawBoundingBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Options.
        /// </summary>
        internal static string CommandOptions {
            get {
                return ResourceManager.GetString("CommandOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Points.
        /// </summary>
        internal static string ConnectionPoints {
            get {
                return ResourceManager.GetString("ConnectionPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector Settings.
        /// </summary>
        internal static string ConnectorGroup {
            get {
                return ResourceManager.GetString("ConnectorGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector Style.
        /// </summary>
        internal static string ConnectorStyle {
            get {
                return ResourceManager.GetString("ConnectorStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directed Graph.
        /// </summary>
        internal static string DirectedGraph {
            get {
                return ResourceManager.GetString("DirectedGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Bounding Boxes.
        /// </summary>
        internal static string DrawBoundingBoxes {
            get {
                return ResourceManager.GetString("DrawBoundingBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Positions.
        /// </summary>
        internal static string ExportPositions {
            get {
                return ResourceManager.GetString("ExportPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Language.
        /// </summary>
        internal static string ExtensionLanguage {
            get {
                return ResourceManager.GetString("ExtensionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-in does not guarantee stability if files are larger than the file size limit..
        /// </summary>
        internal static string FileLimitTurnedOffWarningLiabilityWaiver {
            get {
                return ResourceManager.GetString("FileLimitTurnedOffWarningLiabilityWaiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed. Please reboot Visio for changes to occur..
        /// </summary>
        internal static string LanguageChangedNeedRebootWarning {
            get {
                return ResourceManager.GetString("LanguageChangedNeedRebootWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphViz Parameter Settings.
        /// </summary>
        internal static string LayoutGroup {
            get {
                return ResourceManager.GetString("LayoutGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit File Size.
        /// </summary>
        internal static string LimitFileSize {
            get {
                return ResourceManager.GetString("LimitFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlap Handling.
        /// </summary>
        internal static string OverlapHandling {
            get {
                return ResourceManager.GetString("OverlapHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Seed.
        /// </summary>
        internal static string RandomSeed {
            get {
                return ResourceManager.GetString("RandomSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank Direction.
        /// </summary>
        internal static string RankDirection {
            get {
                return ResourceManager.GetString("RankDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict Mode.
        /// </summary>
        internal static string StrictMode {
            get {
                return ResourceManager.GetString("StrictMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update While Drawing.
        /// </summary>
        internal static string UpdateWhileDrawing {
            get {
                return ResourceManager.GetString("UpdateWhileDrawing", resourceCulture);
            }
        }
    }
}
